// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: service.proto

package agboxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SandboxState int32

const (
	SandboxState_SANDBOX_STATE_UNSPECIFIED SandboxState = 0
	SandboxState_SANDBOX_STATE_PENDING     SandboxState = 1
	SandboxState_SANDBOX_STATE_READY       SandboxState = 2
	SandboxState_SANDBOX_STATE_FAILED      SandboxState = 3
	SandboxState_SANDBOX_STATE_STOPPED     SandboxState = 4
	SandboxState_SANDBOX_STATE_DELETING    SandboxState = 5
	SandboxState_SANDBOX_STATE_DELETED     SandboxState = 6
)

// Enum value maps for SandboxState.
var (
	SandboxState_name = map[int32]string{
		0: "SANDBOX_STATE_UNSPECIFIED",
		1: "SANDBOX_STATE_PENDING",
		2: "SANDBOX_STATE_READY",
		3: "SANDBOX_STATE_FAILED",
		4: "SANDBOX_STATE_STOPPED",
		5: "SANDBOX_STATE_DELETING",
		6: "SANDBOX_STATE_DELETED",
	}
	SandboxState_value = map[string]int32{
		"SANDBOX_STATE_UNSPECIFIED": 0,
		"SANDBOX_STATE_PENDING":     1,
		"SANDBOX_STATE_READY":       2,
		"SANDBOX_STATE_FAILED":      3,
		"SANDBOX_STATE_STOPPED":     4,
		"SANDBOX_STATE_DELETING":    5,
		"SANDBOX_STATE_DELETED":     6,
	}
)

func (x SandboxState) Enum() *SandboxState {
	p := new(SandboxState)
	*p = x
	return p
}

func (x SandboxState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SandboxState) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[0].Descriptor()
}

func (SandboxState) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[0]
}

func (x SandboxState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SandboxState.Descriptor instead.
func (SandboxState) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED   EventType = 0
	EventType_SANDBOX_ACCEPTED         EventType = 1
	EventType_SANDBOX_PREPARING        EventType = 2
	EventType_SANDBOX_DEPENDENCY_READY EventType = 3
	EventType_SANDBOX_READY            EventType = 4
	EventType_SANDBOX_FAILED           EventType = 5
	EventType_SANDBOX_STOP_REQUESTED   EventType = 6
	EventType_SANDBOX_STOPPED          EventType = 7
	EventType_SANDBOX_DELETE_REQUESTED EventType = 8
	EventType_SANDBOX_DELETED          EventType = 9
	EventType_EXEC_STARTED             EventType = 10
	EventType_EXEC_FINISHED            EventType = 11
	EventType_EXEC_FAILED              EventType = 12
	EventType_EXEC_CANCELLED           EventType = 13
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "EVENT_TYPE_UNSPECIFIED",
		1:  "SANDBOX_ACCEPTED",
		2:  "SANDBOX_PREPARING",
		3:  "SANDBOX_DEPENDENCY_READY",
		4:  "SANDBOX_READY",
		5:  "SANDBOX_FAILED",
		6:  "SANDBOX_STOP_REQUESTED",
		7:  "SANDBOX_STOPPED",
		8:  "SANDBOX_DELETE_REQUESTED",
		9:  "SANDBOX_DELETED",
		10: "EXEC_STARTED",
		11: "EXEC_FINISHED",
		12: "EXEC_FAILED",
		13: "EXEC_CANCELLED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":   0,
		"SANDBOX_ACCEPTED":         1,
		"SANDBOX_PREPARING":        2,
		"SANDBOX_DEPENDENCY_READY": 3,
		"SANDBOX_READY":            4,
		"SANDBOX_FAILED":           5,
		"SANDBOX_STOP_REQUESTED":   6,
		"SANDBOX_STOPPED":          7,
		"SANDBOX_DELETE_REQUESTED": 8,
		"SANDBOX_DELETED":          9,
		"EXEC_STARTED":             10,
		"EXEC_FINISHED":            11,
		"EXEC_FAILED":              12,
		"EXEC_CANCELLED":           13,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[1].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[1]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

type ExecState int32

const (
	ExecState_EXEC_STATE_UNSPECIFIED ExecState = 0
	ExecState_EXEC_STATE_RUNNING     ExecState = 1
	ExecState_EXEC_STATE_FINISHED    ExecState = 2
	ExecState_EXEC_STATE_FAILED      ExecState = 3
	ExecState_EXEC_STATE_CANCELLED   ExecState = 4
)

// Enum value maps for ExecState.
var (
	ExecState_name = map[int32]string{
		0: "EXEC_STATE_UNSPECIFIED",
		1: "EXEC_STATE_RUNNING",
		2: "EXEC_STATE_FINISHED",
		3: "EXEC_STATE_FAILED",
		4: "EXEC_STATE_CANCELLED",
	}
	ExecState_value = map[string]int32{
		"EXEC_STATE_UNSPECIFIED": 0,
		"EXEC_STATE_RUNNING":     1,
		"EXEC_STATE_FINISHED":    2,
		"EXEC_STATE_FAILED":      3,
		"EXEC_STATE_CANCELLED":   4,
	}
)

func (x ExecState) Enum() *ExecState {
	p := new(ExecState)
	*p = x
	return p
}

func (x ExecState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecState) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[2].Descriptor()
}

func (ExecState) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[2]
}

func (x ExecState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecState.Descriptor instead.
func (ExecState) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

type ProjectionMountMode int32

const (
	ProjectionMountMode_PROJECTION_MOUNT_MODE_UNSPECIFIED ProjectionMountMode = 0
	ProjectionMountMode_PROJECTION_MOUNT_MODE_BIND        ProjectionMountMode = 1
	ProjectionMountMode_PROJECTION_MOUNT_MODE_SHADOW_COPY ProjectionMountMode = 2
)

// Enum value maps for ProjectionMountMode.
var (
	ProjectionMountMode_name = map[int32]string{
		0: "PROJECTION_MOUNT_MODE_UNSPECIFIED",
		1: "PROJECTION_MOUNT_MODE_BIND",
		2: "PROJECTION_MOUNT_MODE_SHADOW_COPY",
	}
	ProjectionMountMode_value = map[string]int32{
		"PROJECTION_MOUNT_MODE_UNSPECIFIED": 0,
		"PROJECTION_MOUNT_MODE_BIND":        1,
		"PROJECTION_MOUNT_MODE_SHADOW_COPY": 2,
	}
)

func (x ProjectionMountMode) Enum() *ProjectionMountMode {
	p := new(ProjectionMountMode)
	*p = x
	return p
}

func (x ProjectionMountMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProjectionMountMode) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[3].Descriptor()
}

func (ProjectionMountMode) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[3]
}

func (x ProjectionMountMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProjectionMountMode.Descriptor instead.
func (ProjectionMountMode) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

type WorkspaceMaterializationMode int32

const (
	WorkspaceMaterializationMode_WORKSPACE_MATERIALIZATION_MODE_UNSPECIFIED  WorkspaceMaterializationMode = 0
	WorkspaceMaterializationMode_WORKSPACE_MATERIALIZATION_MODE_DURABLE_COPY WorkspaceMaterializationMode = 1
	WorkspaceMaterializationMode_WORKSPACE_MATERIALIZATION_MODE_BIND         WorkspaceMaterializationMode = 2
)

// Enum value maps for WorkspaceMaterializationMode.
var (
	WorkspaceMaterializationMode_name = map[int32]string{
		0: "WORKSPACE_MATERIALIZATION_MODE_UNSPECIFIED",
		1: "WORKSPACE_MATERIALIZATION_MODE_DURABLE_COPY",
		2: "WORKSPACE_MATERIALIZATION_MODE_BIND",
	}
	WorkspaceMaterializationMode_value = map[string]int32{
		"WORKSPACE_MATERIALIZATION_MODE_UNSPECIFIED":  0,
		"WORKSPACE_MATERIALIZATION_MODE_DURABLE_COPY": 1,
		"WORKSPACE_MATERIALIZATION_MODE_BIND":         2,
	}
)

func (x WorkspaceMaterializationMode) Enum() *WorkspaceMaterializationMode {
	p := new(WorkspaceMaterializationMode)
	*p = x
	return p
}

func (x WorkspaceMaterializationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkspaceMaterializationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[4].Descriptor()
}

func (WorkspaceMaterializationMode) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[4]
}

func (x WorkspaceMaterializationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkspaceMaterializationMode.Descriptor instead.
func (WorkspaceMaterializationMode) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Daemon        string                 `protobuf:"bytes,2,opt,name=daemon,proto3" json:"daemon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingResponse) GetDaemon() string {
	if x != nil {
		return x.Daemon
	}
	return ""
}

type SandboxOwner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       string                 `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	OwnerType     string                 `protobuf:"bytes,2,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxOwner) Reset() {
	*x = SandboxOwner{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxOwner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxOwner) ProtoMessage() {}

func (x *SandboxOwner) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxOwner.ProtoReflect.Descriptor instead.
func (*SandboxOwner) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *SandboxOwner) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *SandboxOwner) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

func (x *SandboxOwner) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type CallerMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       string                 `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RunId         string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallerMetadata) Reset() {
	*x = CallerMetadata{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallerMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallerMetadata) ProtoMessage() {}

func (x *CallerMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallerMetadata.ProtoReflect.Descriptor instead.
func (*CallerMetadata) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *CallerMetadata) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *CallerMetadata) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CallerMetadata) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CacheProjectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CacheId       string                 `protobuf:"bytes,1,opt,name=cache_id,json=cacheId,proto3" json:"cache_id,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheProjectionRequest) Reset() {
	*x = CacheProjectionRequest{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheProjectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheProjectionRequest) ProtoMessage() {}

func (x *CacheProjectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheProjectionRequest.ProtoReflect.Descriptor instead.
func (*CacheProjectionRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *CacheProjectionRequest) GetCacheId() string {
	if x != nil {
		return x.CacheId
	}
	return ""
}

func (x *CacheProjectionRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ToolingProjectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapabilityId  string                 `protobuf:"bytes,1,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	Writable      bool                   `protobuf:"varint,2,opt,name=writable,proto3" json:"writable,omitempty"`
	SourcePath    string                 `protobuf:"bytes,3,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	TargetPath    string                 `protobuf:"bytes,4,opt,name=target_path,json=targetPath,proto3" json:"target_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolingProjectionRequest) Reset() {
	*x = ToolingProjectionRequest{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolingProjectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolingProjectionRequest) ProtoMessage() {}

func (x *ToolingProjectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolingProjectionRequest.ProtoReflect.Descriptor instead.
func (*ToolingProjectionRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *ToolingProjectionRequest) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *ToolingProjectionRequest) GetWritable() bool {
	if x != nil {
		return x.Writable
	}
	return false
}

func (x *ToolingProjectionRequest) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *ToolingProjectionRequest) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

type DependencySpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DependencyName string                 `protobuf:"bytes,1,opt,name=dependency_name,json=dependencyName,proto3" json:"dependency_name,omitempty"`
	Image          string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	NetworkAlias   string                 `protobuf:"bytes,3,opt,name=network_alias,json=networkAlias,proto3" json:"network_alias,omitempty"`
	Environment    []*KeyValue            `protobuf:"bytes,4,rep,name=environment,proto3" json:"environment,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DependencySpec) Reset() {
	*x = DependencySpec{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependencySpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencySpec) ProtoMessage() {}

func (x *DependencySpec) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencySpec.ProtoReflect.Descriptor instead.
func (*DependencySpec) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *DependencySpec) GetDependencyName() string {
	if x != nil {
		return x.DependencyName
	}
	return ""
}

func (x *DependencySpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *DependencySpec) GetNetworkAlias() string {
	if x != nil {
		return x.NetworkAlias
	}
	return ""
}

func (x *DependencySpec) GetEnvironment() []*KeyValue {
	if x != nil {
		return x.Environment
	}
	return nil
}

type MountSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Writable      bool                   `protobuf:"varint,3,opt,name=writable,proto3" json:"writable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountSpec) Reset() {
	*x = MountSpec{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountSpec) ProtoMessage() {}

func (x *MountSpec) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountSpec.ProtoReflect.Descriptor instead.
func (*MountSpec) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *MountSpec) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *MountSpec) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *MountSpec) GetWritable() bool {
	if x != nil {
		return x.Writable
	}
	return false
}

type CopySpec struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Source          string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target          string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	ExcludePatterns []string               `protobuf:"bytes,3,rep,name=exclude_patterns,json=excludePatterns,proto3" json:"exclude_patterns,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CopySpec) Reset() {
	*x = CopySpec{}
	mi := &file_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopySpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopySpec) ProtoMessage() {}

func (x *CopySpec) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopySpec.ProtoReflect.Descriptor instead.
func (*CopySpec) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

func (x *CopySpec) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CopySpec) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *CopySpec) GetExcludePatterns() []string {
	if x != nil {
		return x.ExcludePatterns
	}
	return nil
}

type WorkspaceSpec struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Path          string                       `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          WorkspaceMaterializationMode `protobuf:"varint,2,opt,name=mode,proto3,enum=agbox.v1.WorkspaceMaterializationMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceSpec) Reset() {
	*x = WorkspaceSpec{}
	mi := &file_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceSpec) ProtoMessage() {}

func (x *WorkspaceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceSpec.ProtoReflect.Descriptor instead.
func (*WorkspaceSpec) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{10}
}

func (x *WorkspaceSpec) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WorkspaceSpec) GetMode() WorkspaceMaterializationMode {
	if x != nil {
		return x.Mode
	}
	return WorkspaceMaterializationMode_WORKSPACE_MATERIALIZATION_MODE_UNSPECIFIED
}

type CreateSpec struct {
	state              protoimpl.MessageState      `protogen:"open.v1"`
	Workspace          *WorkspaceSpec              `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	CacheProjections   []*CacheProjectionRequest   `protobuf:"bytes,2,rep,name=cache_projections,json=cacheProjections,proto3" json:"cache_projections,omitempty"`
	ToolingProjections []*ToolingProjectionRequest `protobuf:"bytes,3,rep,name=tooling_projections,json=toolingProjections,proto3" json:"tooling_projections,omitempty"`
	Dependencies       []*DependencySpec           `protobuf:"bytes,4,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	Image              string                      `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Mounts             []*MountSpec                `protobuf:"bytes,6,rep,name=mounts,proto3" json:"mounts,omitempty"`
	Copies             []*CopySpec                 `protobuf:"bytes,7,rep,name=copies,proto3" json:"copies,omitempty"`
	BuiltinResources   []string                    `protobuf:"bytes,8,rep,name=builtin_resources,json=builtinResources,proto3" json:"builtin_resources,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateSpec) Reset() {
	*x = CreateSpec{}
	mi := &file_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpec) ProtoMessage() {}

func (x *CreateSpec) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpec.ProtoReflect.Descriptor instead.
func (*CreateSpec) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{11}
}

func (x *CreateSpec) GetWorkspace() *WorkspaceSpec {
	if x != nil {
		return x.Workspace
	}
	return nil
}

func (x *CreateSpec) GetCacheProjections() []*CacheProjectionRequest {
	if x != nil {
		return x.CacheProjections
	}
	return nil
}

func (x *CreateSpec) GetToolingProjections() []*ToolingProjectionRequest {
	if x != nil {
		return x.ToolingProjections
	}
	return nil
}

func (x *CreateSpec) GetDependencies() []*DependencySpec {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *CreateSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateSpec) GetMounts() []*MountSpec {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *CreateSpec) GetCopies() []*CopySpec {
	if x != nil {
		return x.Copies
	}
	return nil
}

func (x *CreateSpec) GetBuiltinResources() []string {
	if x != nil {
		return x.BuiltinResources
	}
	return nil
}

type ResolvedProjectionHandle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapabilityId  string                 `protobuf:"bytes,1,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	SourcePath    string                 `protobuf:"bytes,2,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	TargetPath    string                 `protobuf:"bytes,3,opt,name=target_path,json=targetPath,proto3" json:"target_path,omitempty"`
	MountMode     ProjectionMountMode    `protobuf:"varint,4,opt,name=mount_mode,json=mountMode,proto3,enum=agbox.v1.ProjectionMountMode" json:"mount_mode,omitempty"`
	Writable      bool                   `protobuf:"varint,5,opt,name=writable,proto3" json:"writable,omitempty"`
	WriteBack     bool                   `protobuf:"varint,6,opt,name=write_back,json=writeBack,proto3" json:"write_back,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvedProjectionHandle) Reset() {
	*x = ResolvedProjectionHandle{}
	mi := &file_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedProjectionHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedProjectionHandle) ProtoMessage() {}

func (x *ResolvedProjectionHandle) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedProjectionHandle.ProtoReflect.Descriptor instead.
func (*ResolvedProjectionHandle) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{12}
}

func (x *ResolvedProjectionHandle) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *ResolvedProjectionHandle) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *ResolvedProjectionHandle) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

func (x *ResolvedProjectionHandle) GetMountMode() ProjectionMountMode {
	if x != nil {
		return x.MountMode
	}
	return ProjectionMountMode_PROJECTION_MOUNT_MODE_UNSPECIFIED
}

func (x *ResolvedProjectionHandle) GetWritable() bool {
	if x != nil {
		return x.Writable
	}
	return false
}

func (x *ResolvedProjectionHandle) GetWriteBack() bool {
	if x != nil {
		return x.WriteBack
	}
	return false
}

type SandboxHandle struct {
	state                      protoimpl.MessageState      `protogen:"open.v1"`
	SandboxId                  string                      `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Owner                      *SandboxOwner               `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	State                      SandboxState                `protobuf:"varint,3,opt,name=state,proto3,enum=agbox.v1.SandboxState" json:"state,omitempty"`
	ResolvedToolingProjections []*ResolvedProjectionHandle `protobuf:"bytes,4,rep,name=resolved_tooling_projections,json=resolvedToolingProjections,proto3" json:"resolved_tooling_projections,omitempty"`
	Dependencies               []*DependencySpec           `protobuf:"bytes,5,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	LastEventCursor            string                      `protobuf:"bytes,6,opt,name=last_event_cursor,json=lastEventCursor,proto3" json:"last_event_cursor,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *SandboxHandle) Reset() {
	*x = SandboxHandle{}
	mi := &file_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxHandle) ProtoMessage() {}

func (x *SandboxHandle) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxHandle.ProtoReflect.Descriptor instead.
func (*SandboxHandle) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{13}
}

func (x *SandboxHandle) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SandboxHandle) GetOwner() *SandboxOwner {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *SandboxHandle) GetState() SandboxState {
	if x != nil {
		return x.State
	}
	return SandboxState_SANDBOX_STATE_UNSPECIFIED
}

func (x *SandboxHandle) GetResolvedToolingProjections() []*ResolvedProjectionHandle {
	if x != nil {
		return x.ResolvedToolingProjections
	}
	return nil
}

func (x *SandboxHandle) GetDependencies() []*DependencySpec {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *SandboxHandle) GetLastEventCursor() string {
	if x != nil {
		return x.LastEventCursor
	}
	return ""
}

type SandboxEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventId        string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Sequence       uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Cursor         string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	SandboxId      string                 `protobuf:"bytes,4,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	EventType      EventType              `protobuf:"varint,5,opt,name=event_type,json=eventType,proto3,enum=agbox.v1.EventType" json:"event_type,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Replay         bool                   `protobuf:"varint,7,opt,name=replay,proto3" json:"replay,omitempty"`
	Snapshot       bool                   `protobuf:"varint,8,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Phase          string                 `protobuf:"bytes,9,opt,name=phase,proto3" json:"phase,omitempty"`
	DependencyName string                 `protobuf:"bytes,10,opt,name=dependency_name,json=dependencyName,proto3" json:"dependency_name,omitempty"`
	ErrorCode      string                 `protobuf:"bytes,11,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,12,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Reason         string                 `protobuf:"bytes,13,opt,name=reason,proto3" json:"reason,omitempty"`
	ExecId         string                 `protobuf:"bytes,14,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	ExitCode       int32                  `protobuf:"varint,15,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	SandboxState   SandboxState           `protobuf:"varint,16,opt,name=sandbox_state,json=sandboxState,proto3,enum=agbox.v1.SandboxState" json:"sandbox_state,omitempty"`
	ExecState      ExecState              `protobuf:"varint,17,opt,name=exec_state,json=execState,proto3,enum=agbox.v1.ExecState" json:"exec_state,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SandboxEvent) Reset() {
	*x = SandboxEvent{}
	mi := &file_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxEvent) ProtoMessage() {}

func (x *SandboxEvent) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxEvent.ProtoReflect.Descriptor instead.
func (*SandboxEvent) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{14}
}

func (x *SandboxEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *SandboxEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *SandboxEvent) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *SandboxEvent) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SandboxEvent) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *SandboxEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *SandboxEvent) GetReplay() bool {
	if x != nil {
		return x.Replay
	}
	return false
}

func (x *SandboxEvent) GetSnapshot() bool {
	if x != nil {
		return x.Snapshot
	}
	return false
}

func (x *SandboxEvent) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *SandboxEvent) GetDependencyName() string {
	if x != nil {
		return x.DependencyName
	}
	return ""
}

func (x *SandboxEvent) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *SandboxEvent) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SandboxEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SandboxEvent) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *SandboxEvent) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *SandboxEvent) GetSandboxState() SandboxState {
	if x != nil {
		return x.SandboxState
	}
	return SandboxState_SANDBOX_STATE_UNSPECIFIED
}

func (x *SandboxEvent) GetExecState() ExecState {
	if x != nil {
		return x.ExecState
	}
	return ExecState_EXEC_STATE_UNSPECIFIED
}

type ExecStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecId        string                 `protobuf:"bytes,1,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	SandboxId     string                 `protobuf:"bytes,2,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	State         ExecState              `protobuf:"varint,3,opt,name=state,proto3,enum=agbox.v1.ExecState" json:"state,omitempty"`
	Command       []string               `protobuf:"bytes,4,rep,name=command,proto3" json:"command,omitempty"`
	Cwd           string                 `protobuf:"bytes,5,opt,name=cwd,proto3" json:"cwd,omitempty"`
	EnvOverrides  []*KeyValue            `protobuf:"bytes,6,rep,name=env_overrides,json=envOverrides,proto3" json:"env_overrides,omitempty"`
	ExitCode      int32                  `protobuf:"varint,7,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	Stdout        string                 `protobuf:"bytes,9,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,10,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecStatus) Reset() {
	*x = ExecStatus{}
	mi := &file_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStatus) ProtoMessage() {}

func (x *ExecStatus) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStatus.ProtoReflect.Descriptor instead.
func (*ExecStatus) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{15}
}

func (x *ExecStatus) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *ExecStatus) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ExecStatus) GetState() ExecState {
	if x != nil {
		return x.State
	}
	return ExecState_EXEC_STATE_UNSPECIFIED
}

func (x *ExecStatus) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ExecStatus) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ExecStatus) GetEnvOverrides() []*KeyValue {
	if x != nil {
		return x.EnvOverrides
	}
	return nil
}

func (x *ExecStatus) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecStatus) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecStatus) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

type CreateSandboxRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SandboxOwner   *SandboxOwner          `protobuf:"bytes,1,opt,name=sandbox_owner,json=sandboxOwner,proto3" json:"sandbox_owner,omitempty"`
	CreateSpec     *CreateSpec            `protobuf:"bytes,2,opt,name=create_spec,json=createSpec,proto3" json:"create_spec,omitempty"`
	CallerMetadata *CallerMetadata        `protobuf:"bytes,3,opt,name=caller_metadata,json=callerMetadata,proto3" json:"caller_metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateSandboxRequest) Reset() {
	*x = CreateSandboxRequest{}
	mi := &file_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxRequest) ProtoMessage() {}

func (x *CreateSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxRequest.ProtoReflect.Descriptor instead.
func (*CreateSandboxRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{16}
}

func (x *CreateSandboxRequest) GetSandboxOwner() *SandboxOwner {
	if x != nil {
		return x.SandboxOwner
	}
	return nil
}

func (x *CreateSandboxRequest) GetCreateSpec() *CreateSpec {
	if x != nil {
		return x.CreateSpec
	}
	return nil
}

func (x *CreateSandboxRequest) GetCallerMetadata() *CallerMetadata {
	if x != nil {
		return x.CallerMetadata
	}
	return nil
}

type CreateSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	InitialState  SandboxState           `protobuf:"varint,2,opt,name=initial_state,json=initialState,proto3,enum=agbox.v1.SandboxState" json:"initial_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxResponse) Reset() {
	*x = CreateSandboxResponse{}
	mi := &file_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxResponse) ProtoMessage() {}

func (x *CreateSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxResponse.ProtoReflect.Descriptor instead.
func (*CreateSandboxResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{17}
}

func (x *CreateSandboxResponse) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *CreateSandboxResponse) GetInitialState() SandboxState {
	if x != nil {
		return x.InitialState
	}
	return SandboxState_SANDBOX_STATE_UNSPECIFIED
}

type GetSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxRequest) Reset() {
	*x = GetSandboxRequest{}
	mi := &file_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxRequest) ProtoMessage() {}

func (x *GetSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxRequest.ProtoReflect.Descriptor instead.
func (*GetSandboxRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type GetSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandbox       *SandboxHandle         `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxResponse) Reset() {
	*x = GetSandboxResponse{}
	mi := &file_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxResponse) ProtoMessage() {}

func (x *GetSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxResponse.ProtoReflect.Descriptor instead.
func (*GetSandboxResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetSandboxResponse) GetSandbox() *SandboxHandle {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

type ListSandboxesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Owner          *SandboxOwner          `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	IncludeDeleted bool                   `protobuf:"varint,2,opt,name=include_deleted,json=includeDeleted,proto3" json:"include_deleted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListSandboxesRequest) Reset() {
	*x = ListSandboxesRequest{}
	mi := &file_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesRequest) ProtoMessage() {}

func (x *ListSandboxesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesRequest.ProtoReflect.Descriptor instead.
func (*ListSandboxesRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{20}
}

func (x *ListSandboxesRequest) GetOwner() *SandboxOwner {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *ListSandboxesRequest) GetIncludeDeleted() bool {
	if x != nil {
		return x.IncludeDeleted
	}
	return false
}

type ListSandboxesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandboxes     []*SandboxHandle       `protobuf:"bytes,1,rep,name=sandboxes,proto3" json:"sandboxes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesResponse) Reset() {
	*x = ListSandboxesResponse{}
	mi := &file_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesResponse) ProtoMessage() {}

func (x *ListSandboxesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesResponse.ProtoReflect.Descriptor instead.
func (*ListSandboxesResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{21}
}

func (x *ListSandboxesResponse) GetSandboxes() []*SandboxHandle {
	if x != nil {
		return x.Sandboxes
	}
	return nil
}

type ResumeSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeSandboxRequest) Reset() {
	*x = ResumeSandboxRequest{}
	mi := &file_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeSandboxRequest) ProtoMessage() {}

func (x *ResumeSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeSandboxRequest.ProtoReflect.Descriptor instead.
func (*ResumeSandboxRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{22}
}

func (x *ResumeSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type StopSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSandboxRequest) Reset() {
	*x = StopSandboxRequest{}
	mi := &file_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSandboxRequest) ProtoMessage() {}

func (x *StopSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSandboxRequest.ProtoReflect.Descriptor instead.
func (*StopSandboxRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{23}
}

func (x *StopSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type DeleteSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSandboxRequest) Reset() {
	*x = DeleteSandboxRequest{}
	mi := &file_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSandboxRequest) ProtoMessage() {}

func (x *DeleteSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSandboxRequest.ProtoReflect.Descriptor instead.
func (*DeleteSandboxRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type AcceptedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptedResponse) Reset() {
	*x = AcceptedResponse{}
	mi := &file_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptedResponse) ProtoMessage() {}

func (x *AcceptedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptedResponse.ProtoReflect.Descriptor instead.
func (*AcceptedResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{25}
}

func (x *AcceptedResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type SubscribeSandboxEventsRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SandboxId              string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	FromCursor             string                 `protobuf:"bytes,2,opt,name=from_cursor,json=fromCursor,proto3" json:"from_cursor,omitempty"`
	IncludeCurrentSnapshot bool                   `protobuf:"varint,3,opt,name=include_current_snapshot,json=includeCurrentSnapshot,proto3" json:"include_current_snapshot,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SubscribeSandboxEventsRequest) Reset() {
	*x = SubscribeSandboxEventsRequest{}
	mi := &file_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeSandboxEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeSandboxEventsRequest) ProtoMessage() {}

func (x *SubscribeSandboxEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeSandboxEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeSandboxEventsRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{26}
}

func (x *SubscribeSandboxEventsRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SubscribeSandboxEventsRequest) GetFromCursor() string {
	if x != nil {
		return x.FromCursor
	}
	return ""
}

func (x *SubscribeSandboxEventsRequest) GetIncludeCurrentSnapshot() bool {
	if x != nil {
		return x.IncludeCurrentSnapshot
	}
	return false
}

type CreateExecRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SandboxId      string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Command        []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Cwd            string                 `protobuf:"bytes,3,opt,name=cwd,proto3" json:"cwd,omitempty"`
	EnvOverrides   []*KeyValue            `protobuf:"bytes,4,rep,name=env_overrides,json=envOverrides,proto3" json:"env_overrides,omitempty"`
	CallerMetadata *CallerMetadata        `protobuf:"bytes,5,opt,name=caller_metadata,json=callerMetadata,proto3" json:"caller_metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateExecRequest) Reset() {
	*x = CreateExecRequest{}
	mi := &file_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExecRequest) ProtoMessage() {}

func (x *CreateExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExecRequest.ProtoReflect.Descriptor instead.
func (*CreateExecRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{27}
}

func (x *CreateExecRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *CreateExecRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *CreateExecRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *CreateExecRequest) GetEnvOverrides() []*KeyValue {
	if x != nil {
		return x.EnvOverrides
	}
	return nil
}

func (x *CreateExecRequest) GetCallerMetadata() *CallerMetadata {
	if x != nil {
		return x.CallerMetadata
	}
	return nil
}

type CreateExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecId        string                 `protobuf:"bytes,1,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExecResponse) Reset() {
	*x = CreateExecResponse{}
	mi := &file_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExecResponse) ProtoMessage() {}

func (x *CreateExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExecResponse.ProtoReflect.Descriptor instead.
func (*CreateExecResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{28}
}

func (x *CreateExecResponse) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

type CancelExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecId        string                 `protobuf:"bytes,1,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelExecRequest) Reset() {
	*x = CancelExecRequest{}
	mi := &file_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelExecRequest) ProtoMessage() {}

func (x *CancelExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelExecRequest.ProtoReflect.Descriptor instead.
func (*CancelExecRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{29}
}

func (x *CancelExecRequest) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

type GetExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecId        string                 `protobuf:"bytes,1,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecRequest) Reset() {
	*x = GetExecRequest{}
	mi := &file_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecRequest) ProtoMessage() {}

func (x *GetExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecRequest.ProtoReflect.Descriptor instead.
func (*GetExecRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{30}
}

func (x *GetExecRequest) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

type GetExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exec          *ExecStatus            `protobuf:"bytes,1,opt,name=exec,proto3" json:"exec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecResponse) Reset() {
	*x = GetExecResponse{}
	mi := &file_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecResponse) ProtoMessage() {}

func (x *GetExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecResponse.ProtoReflect.Descriptor instead.
func (*GetExecResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{31}
}

func (x *GetExecResponse) GetExec() *ExecStatus {
	if x != nil {
		return x.Exec
	}
	return nil
}

type ListActiveExecsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveExecsRequest) Reset() {
	*x = ListActiveExecsRequest{}
	mi := &file_service_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveExecsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveExecsRequest) ProtoMessage() {}

func (x *ListActiveExecsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveExecsRequest.ProtoReflect.Descriptor instead.
func (*ListActiveExecsRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{32}
}

func (x *ListActiveExecsRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type ListActiveExecsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Execs         []*ExecStatus          `protobuf:"bytes,1,rep,name=execs,proto3" json:"execs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveExecsResponse) Reset() {
	*x = ListActiveExecsResponse{}
	mi := &file_service_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveExecsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveExecsResponse) ProtoMessage() {}

func (x *ListActiveExecsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveExecsResponse.ProtoReflect.Descriptor instead.
func (*ListActiveExecsResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{33}
}

func (x *ListActiveExecsResponse) GetExecs() []*ExecStatus {
	if x != nil {
		return x.Execs
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\bagbox.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\r\n" +
	"\vPingRequest\"@\n" +
	"\fPingResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06daemon\x18\x02 \x01(\tR\x06daemon\"b\n" +
	"\fSandboxOwner\x12\x18\n" +
	"\aproduct\x18\x01 \x01(\tR\aproduct\x12\x1d\n" +
	"\n" +
	"owner_type\x18\x02 \x01(\tR\townerType\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\"`\n" +
	"\x0eCallerMetadata\x12\x18\n" +
	"\aproduct\x18\x01 \x01(\tR\aproduct\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\"2\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"M\n" +
	"\x16CacheProjectionRequest\x12\x19\n" +
	"\bcache_id\x18\x01 \x01(\tR\acacheId\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"\x9d\x01\n" +
	"\x18ToolingProjectionRequest\x12#\n" +
	"\rcapability_id\x18\x01 \x01(\tR\fcapabilityId\x12\x1a\n" +
	"\bwritable\x18\x02 \x01(\bR\bwritable\x12\x1f\n" +
	"\vsource_path\x18\x03 \x01(\tR\n" +
	"sourcePath\x12\x1f\n" +
	"\vtarget_path\x18\x04 \x01(\tR\n" +
	"targetPath\"\xaa\x01\n" +
	"\x0eDependencySpec\x12'\n" +
	"\x0fdependency_name\x18\x01 \x01(\tR\x0edependencyName\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12#\n" +
	"\rnetwork_alias\x18\x03 \x01(\tR\fnetworkAlias\x124\n" +
	"\venvironment\x18\x04 \x03(\v2\x12.agbox.v1.KeyValueR\venvironment\"W\n" +
	"\tMountSpec\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1a\n" +
	"\bwritable\x18\x03 \x01(\bR\bwritable\"e\n" +
	"\bCopySpec\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12)\n" +
	"\x10exclude_patterns\x18\x03 \x03(\tR\x0fexcludePatterns\"_\n" +
	"\rWorkspaceSpec\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12:\n" +
	"\x04mode\x18\x02 \x01(\x0e2&.agbox.v1.WorkspaceMaterializationModeR\x04mode\"\xc1\x03\n" +
	"\n" +
	"CreateSpec\x125\n" +
	"\tworkspace\x18\x01 \x01(\v2\x17.agbox.v1.WorkspaceSpecR\tworkspace\x12M\n" +
	"\x11cache_projections\x18\x02 \x03(\v2 .agbox.v1.CacheProjectionRequestR\x10cacheProjections\x12S\n" +
	"\x13tooling_projections\x18\x03 \x03(\v2\".agbox.v1.ToolingProjectionRequestR\x12toolingProjections\x12<\n" +
	"\fdependencies\x18\x04 \x03(\v2\x18.agbox.v1.DependencySpecR\fdependencies\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12+\n" +
	"\x06mounts\x18\x06 \x03(\v2\x13.agbox.v1.MountSpecR\x06mounts\x12*\n" +
	"\x06copies\x18\a \x03(\v2\x12.agbox.v1.CopySpecR\x06copies\x12+\n" +
	"\x11builtin_resources\x18\b \x03(\tR\x10builtinResources\"\xfa\x01\n" +
	"\x18ResolvedProjectionHandle\x12#\n" +
	"\rcapability_id\x18\x01 \x01(\tR\fcapabilityId\x12\x1f\n" +
	"\vsource_path\x18\x02 \x01(\tR\n" +
	"sourcePath\x12\x1f\n" +
	"\vtarget_path\x18\x03 \x01(\tR\n" +
	"targetPath\x12<\n" +
	"\n" +
	"mount_mode\x18\x04 \x01(\x0e2\x1d.agbox.v1.ProjectionMountModeR\tmountMode\x12\x1a\n" +
	"\bwritable\x18\x05 \x01(\bR\bwritable\x12\x1d\n" +
	"\n" +
	"write_back\x18\x06 \x01(\bR\twriteBack\"\xda\x02\n" +
	"\rSandboxHandle\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12,\n" +
	"\x05owner\x18\x02 \x01(\v2\x16.agbox.v1.SandboxOwnerR\x05owner\x12,\n" +
	"\x05state\x18\x03 \x01(\x0e2\x16.agbox.v1.SandboxStateR\x05state\x12d\n" +
	"\x1cresolved_tooling_projections\x18\x04 \x03(\v2\".agbox.v1.ResolvedProjectionHandleR\x1aresolvedToolingProjections\x12<\n" +
	"\fdependencies\x18\x05 \x03(\v2\x18.agbox.v1.DependencySpecR\fdependencies\x12*\n" +
	"\x11last_event_cursor\x18\x06 \x01(\tR\x0flastEventCursor\"\xe3\x04\n" +
	"\fSandboxEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x04 \x01(\tR\tsandboxId\x122\n" +
	"\n" +
	"event_type\x18\x05 \x01(\x0e2\x13.agbox.v1.EventTypeR\teventType\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x16\n" +
	"\x06replay\x18\a \x01(\bR\x06replay\x12\x1a\n" +
	"\bsnapshot\x18\b \x01(\bR\bsnapshot\x12\x14\n" +
	"\x05phase\x18\t \x01(\tR\x05phase\x12'\n" +
	"\x0fdependency_name\x18\n" +
	" \x01(\tR\x0edependencyName\x12\x1d\n" +
	"\n" +
	"error_code\x18\v \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\f \x01(\tR\ferrorMessage\x12\x16\n" +
	"\x06reason\x18\r \x01(\tR\x06reason\x12\x17\n" +
	"\aexec_id\x18\x0e \x01(\tR\x06execId\x12\x1b\n" +
	"\texit_code\x18\x0f \x01(\x05R\bexitCode\x12;\n" +
	"\rsandbox_state\x18\x10 \x01(\x0e2\x16.agbox.v1.SandboxStateR\fsandboxState\x122\n" +
	"\n" +
	"exec_state\x18\x11 \x01(\x0e2\x13.agbox.v1.ExecStateR\texecState\"\xb7\x02\n" +
	"\n" +
	"ExecStatus\x12\x17\n" +
	"\aexec_id\x18\x01 \x01(\tR\x06execId\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x02 \x01(\tR\tsandboxId\x12)\n" +
	"\x05state\x18\x03 \x01(\x0e2\x13.agbox.v1.ExecStateR\x05state\x12\x18\n" +
	"\acommand\x18\x04 \x03(\tR\acommand\x12\x10\n" +
	"\x03cwd\x18\x05 \x01(\tR\x03cwd\x127\n" +
	"\renv_overrides\x18\x06 \x03(\v2\x12.agbox.v1.KeyValueR\fenvOverrides\x12\x1b\n" +
	"\texit_code\x18\a \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12\x16\n" +
	"\x06stdout\x18\t \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\n" +
	" \x01(\tR\x06stderr\"\xcd\x01\n" +
	"\x14CreateSandboxRequest\x12;\n" +
	"\rsandbox_owner\x18\x01 \x01(\v2\x16.agbox.v1.SandboxOwnerR\fsandboxOwner\x125\n" +
	"\vcreate_spec\x18\x02 \x01(\v2\x14.agbox.v1.CreateSpecR\n" +
	"createSpec\x12A\n" +
	"\x0fcaller_metadata\x18\x03 \x01(\v2\x18.agbox.v1.CallerMetadataR\x0ecallerMetadata\"s\n" +
	"\x15CreateSandboxResponse\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12;\n" +
	"\rinitial_state\x18\x02 \x01(\x0e2\x16.agbox.v1.SandboxStateR\finitialState\"2\n" +
	"\x11GetSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"G\n" +
	"\x12GetSandboxResponse\x121\n" +
	"\asandbox\x18\x01 \x01(\v2\x17.agbox.v1.SandboxHandleR\asandbox\"m\n" +
	"\x14ListSandboxesRequest\x12,\n" +
	"\x05owner\x18\x01 \x01(\v2\x16.agbox.v1.SandboxOwnerR\x05owner\x12'\n" +
	"\x0finclude_deleted\x18\x02 \x01(\bR\x0eincludeDeleted\"N\n" +
	"\x15ListSandboxesResponse\x125\n" +
	"\tsandboxes\x18\x01 \x03(\v2\x17.agbox.v1.SandboxHandleR\tsandboxes\"5\n" +
	"\x14ResumeSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"3\n" +
	"\x12StopSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"5\n" +
	"\x14DeleteSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\".\n" +
	"\x10AcceptedResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\x99\x01\n" +
	"\x1dSubscribeSandboxEventsRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x1f\n" +
	"\vfrom_cursor\x18\x02 \x01(\tR\n" +
	"fromCursor\x128\n" +
	"\x18include_current_snapshot\x18\x03 \x01(\bR\x16includeCurrentSnapshot\"\xda\x01\n" +
	"\x11CreateExecRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x10\n" +
	"\x03cwd\x18\x03 \x01(\tR\x03cwd\x127\n" +
	"\renv_overrides\x18\x04 \x03(\v2\x12.agbox.v1.KeyValueR\fenvOverrides\x12A\n" +
	"\x0fcaller_metadata\x18\x05 \x01(\v2\x18.agbox.v1.CallerMetadataR\x0ecallerMetadata\"-\n" +
	"\x12CreateExecResponse\x12\x17\n" +
	"\aexec_id\x18\x01 \x01(\tR\x06execId\",\n" +
	"\x11CancelExecRequest\x12\x17\n" +
	"\aexec_id\x18\x01 \x01(\tR\x06execId\")\n" +
	"\x0eGetExecRequest\x12\x17\n" +
	"\aexec_id\x18\x01 \x01(\tR\x06execId\";\n" +
	"\x0fGetExecResponse\x12(\n" +
	"\x04exec\x18\x01 \x01(\v2\x14.agbox.v1.ExecStatusR\x04exec\"7\n" +
	"\x16ListActiveExecsRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"E\n" +
	"\x17ListActiveExecsResponse\x12*\n" +
	"\x05execs\x18\x01 \x03(\v2\x14.agbox.v1.ExecStatusR\x05execs*\xcd\x01\n" +
	"\fSandboxState\x12\x1d\n" +
	"\x19SANDBOX_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SANDBOX_STATE_PENDING\x10\x01\x12\x17\n" +
	"\x13SANDBOX_STATE_READY\x10\x02\x12\x18\n" +
	"\x14SANDBOX_STATE_FAILED\x10\x03\x12\x19\n" +
	"\x15SANDBOX_STATE_STOPPED\x10\x04\x12\x1a\n" +
	"\x16SANDBOX_STATE_DELETING\x10\x05\x12\x19\n" +
	"\x15SANDBOX_STATE_DELETED\x10\x06*\xc7\x02\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SANDBOX_ACCEPTED\x10\x01\x12\x15\n" +
	"\x11SANDBOX_PREPARING\x10\x02\x12\x1c\n" +
	"\x18SANDBOX_DEPENDENCY_READY\x10\x03\x12\x11\n" +
	"\rSANDBOX_READY\x10\x04\x12\x12\n" +
	"\x0eSANDBOX_FAILED\x10\x05\x12\x1a\n" +
	"\x16SANDBOX_STOP_REQUESTED\x10\x06\x12\x13\n" +
	"\x0fSANDBOX_STOPPED\x10\a\x12\x1c\n" +
	"\x18SANDBOX_DELETE_REQUESTED\x10\b\x12\x13\n" +
	"\x0fSANDBOX_DELETED\x10\t\x12\x10\n" +
	"\fEXEC_STARTED\x10\n" +
	"\x12\x11\n" +
	"\rEXEC_FINISHED\x10\v\x12\x0f\n" +
	"\vEXEC_FAILED\x10\f\x12\x12\n" +
	"\x0eEXEC_CANCELLED\x10\r*\x89\x01\n" +
	"\tExecState\x12\x1a\n" +
	"\x16EXEC_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EXEC_STATE_RUNNING\x10\x01\x12\x17\n" +
	"\x13EXEC_STATE_FINISHED\x10\x02\x12\x15\n" +
	"\x11EXEC_STATE_FAILED\x10\x03\x12\x18\n" +
	"\x14EXEC_STATE_CANCELLED\x10\x04*\x83\x01\n" +
	"\x13ProjectionMountMode\x12%\n" +
	"!PROJECTION_MOUNT_MODE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aPROJECTION_MOUNT_MODE_BIND\x10\x01\x12%\n" +
	"!PROJECTION_MOUNT_MODE_SHADOW_COPY\x10\x02*\xa8\x01\n" +
	"\x1cWorkspaceMaterializationMode\x12.\n" +
	"*WORKSPACE_MATERIALIZATION_MODE_UNSPECIFIED\x10\x00\x12/\n" +
	"+WORKSPACE_MATERIALIZATION_MODE_DURABLE_COPY\x10\x01\x12'\n" +
	"#WORKSPACE_MATERIALIZATION_MODE_BIND\x10\x022\x9c\a\n" +
	"\x0eSandboxService\x125\n" +
	"\x04Ping\x12\x15.agbox.v1.PingRequest\x1a\x16.agbox.v1.PingResponse\x12P\n" +
	"\rCreateSandbox\x12\x1e.agbox.v1.CreateSandboxRequest\x1a\x1f.agbox.v1.CreateSandboxResponse\x12G\n" +
	"\n" +
	"GetSandbox\x12\x1b.agbox.v1.GetSandboxRequest\x1a\x1c.agbox.v1.GetSandboxResponse\x12P\n" +
	"\rListSandboxes\x12\x1e.agbox.v1.ListSandboxesRequest\x1a\x1f.agbox.v1.ListSandboxesResponse\x12K\n" +
	"\rResumeSandbox\x12\x1e.agbox.v1.ResumeSandboxRequest\x1a\x1a.agbox.v1.AcceptedResponse\x12G\n" +
	"\vStopSandbox\x12\x1c.agbox.v1.StopSandboxRequest\x1a\x1a.agbox.v1.AcceptedResponse\x12K\n" +
	"\rDeleteSandbox\x12\x1e.agbox.v1.DeleteSandboxRequest\x1a\x1a.agbox.v1.AcceptedResponse\x12[\n" +
	"\x16SubscribeSandboxEvents\x12'.agbox.v1.SubscribeSandboxEventsRequest\x1a\x16.agbox.v1.SandboxEvent0\x01\x12G\n" +
	"\n" +
	"CreateExec\x12\x1b.agbox.v1.CreateExecRequest\x1a\x1c.agbox.v1.CreateExecResponse\x12E\n" +
	"\n" +
	"CancelExec\x12\x1b.agbox.v1.CancelExecRequest\x1a\x1a.agbox.v1.AcceptedResponse\x12>\n" +
	"\aGetExec\x12\x18.agbox.v1.GetExecRequest\x1a\x19.agbox.v1.GetExecResponse\x12V\n" +
	"\x0fListActiveExecs\x12 .agbox.v1.ListActiveExecsRequest\x1a!.agbox.v1.ListActiveExecsResponseB@Z>github.com/1996fanrui/agents-sandbox/api/proto/agboxv1;agboxv1b\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_service_proto_goTypes = []any{
	(SandboxState)(0),                     // 0: agbox.v1.SandboxState
	(EventType)(0),                        // 1: agbox.v1.EventType
	(ExecState)(0),                        // 2: agbox.v1.ExecState
	(ProjectionMountMode)(0),              // 3: agbox.v1.ProjectionMountMode
	(WorkspaceMaterializationMode)(0),     // 4: agbox.v1.WorkspaceMaterializationMode
	(*PingRequest)(nil),                   // 5: agbox.v1.PingRequest
	(*PingResponse)(nil),                  // 6: agbox.v1.PingResponse
	(*SandboxOwner)(nil),                  // 7: agbox.v1.SandboxOwner
	(*CallerMetadata)(nil),                // 8: agbox.v1.CallerMetadata
	(*KeyValue)(nil),                      // 9: agbox.v1.KeyValue
	(*CacheProjectionRequest)(nil),        // 10: agbox.v1.CacheProjectionRequest
	(*ToolingProjectionRequest)(nil),      // 11: agbox.v1.ToolingProjectionRequest
	(*DependencySpec)(nil),                // 12: agbox.v1.DependencySpec
	(*MountSpec)(nil),                     // 13: agbox.v1.MountSpec
	(*CopySpec)(nil),                      // 14: agbox.v1.CopySpec
	(*WorkspaceSpec)(nil),                 // 15: agbox.v1.WorkspaceSpec
	(*CreateSpec)(nil),                    // 16: agbox.v1.CreateSpec
	(*ResolvedProjectionHandle)(nil),      // 17: agbox.v1.ResolvedProjectionHandle
	(*SandboxHandle)(nil),                 // 18: agbox.v1.SandboxHandle
	(*SandboxEvent)(nil),                  // 19: agbox.v1.SandboxEvent
	(*ExecStatus)(nil),                    // 20: agbox.v1.ExecStatus
	(*CreateSandboxRequest)(nil),          // 21: agbox.v1.CreateSandboxRequest
	(*CreateSandboxResponse)(nil),         // 22: agbox.v1.CreateSandboxResponse
	(*GetSandboxRequest)(nil),             // 23: agbox.v1.GetSandboxRequest
	(*GetSandboxResponse)(nil),            // 24: agbox.v1.GetSandboxResponse
	(*ListSandboxesRequest)(nil),          // 25: agbox.v1.ListSandboxesRequest
	(*ListSandboxesResponse)(nil),         // 26: agbox.v1.ListSandboxesResponse
	(*ResumeSandboxRequest)(nil),          // 27: agbox.v1.ResumeSandboxRequest
	(*StopSandboxRequest)(nil),            // 28: agbox.v1.StopSandboxRequest
	(*DeleteSandboxRequest)(nil),          // 29: agbox.v1.DeleteSandboxRequest
	(*AcceptedResponse)(nil),              // 30: agbox.v1.AcceptedResponse
	(*SubscribeSandboxEventsRequest)(nil), // 31: agbox.v1.SubscribeSandboxEventsRequest
	(*CreateExecRequest)(nil),             // 32: agbox.v1.CreateExecRequest
	(*CreateExecResponse)(nil),            // 33: agbox.v1.CreateExecResponse
	(*CancelExecRequest)(nil),             // 34: agbox.v1.CancelExecRequest
	(*GetExecRequest)(nil),                // 35: agbox.v1.GetExecRequest
	(*GetExecResponse)(nil),               // 36: agbox.v1.GetExecResponse
	(*ListActiveExecsRequest)(nil),        // 37: agbox.v1.ListActiveExecsRequest
	(*ListActiveExecsResponse)(nil),       // 38: agbox.v1.ListActiveExecsResponse
	(*timestamppb.Timestamp)(nil),         // 39: google.protobuf.Timestamp
}
var file_service_proto_depIdxs = []int32{
	9,  // 0: agbox.v1.DependencySpec.environment:type_name -> agbox.v1.KeyValue
	4,  // 1: agbox.v1.WorkspaceSpec.mode:type_name -> agbox.v1.WorkspaceMaterializationMode
	15, // 2: agbox.v1.CreateSpec.workspace:type_name -> agbox.v1.WorkspaceSpec
	10, // 3: agbox.v1.CreateSpec.cache_projections:type_name -> agbox.v1.CacheProjectionRequest
	11, // 4: agbox.v1.CreateSpec.tooling_projections:type_name -> agbox.v1.ToolingProjectionRequest
	12, // 5: agbox.v1.CreateSpec.dependencies:type_name -> agbox.v1.DependencySpec
	13, // 6: agbox.v1.CreateSpec.mounts:type_name -> agbox.v1.MountSpec
	14, // 7: agbox.v1.CreateSpec.copies:type_name -> agbox.v1.CopySpec
	3,  // 8: agbox.v1.ResolvedProjectionHandle.mount_mode:type_name -> agbox.v1.ProjectionMountMode
	7,  // 9: agbox.v1.SandboxHandle.owner:type_name -> agbox.v1.SandboxOwner
	0,  // 10: agbox.v1.SandboxHandle.state:type_name -> agbox.v1.SandboxState
	17, // 11: agbox.v1.SandboxHandle.resolved_tooling_projections:type_name -> agbox.v1.ResolvedProjectionHandle
	12, // 12: agbox.v1.SandboxHandle.dependencies:type_name -> agbox.v1.DependencySpec
	1,  // 13: agbox.v1.SandboxEvent.event_type:type_name -> agbox.v1.EventType
	39, // 14: agbox.v1.SandboxEvent.occurred_at:type_name -> google.protobuf.Timestamp
	0,  // 15: agbox.v1.SandboxEvent.sandbox_state:type_name -> agbox.v1.SandboxState
	2,  // 16: agbox.v1.SandboxEvent.exec_state:type_name -> agbox.v1.ExecState
	2,  // 17: agbox.v1.ExecStatus.state:type_name -> agbox.v1.ExecState
	9,  // 18: agbox.v1.ExecStatus.env_overrides:type_name -> agbox.v1.KeyValue
	7,  // 19: agbox.v1.CreateSandboxRequest.sandbox_owner:type_name -> agbox.v1.SandboxOwner
	16, // 20: agbox.v1.CreateSandboxRequest.create_spec:type_name -> agbox.v1.CreateSpec
	8,  // 21: agbox.v1.CreateSandboxRequest.caller_metadata:type_name -> agbox.v1.CallerMetadata
	0,  // 22: agbox.v1.CreateSandboxResponse.initial_state:type_name -> agbox.v1.SandboxState
	18, // 23: agbox.v1.GetSandboxResponse.sandbox:type_name -> agbox.v1.SandboxHandle
	7,  // 24: agbox.v1.ListSandboxesRequest.owner:type_name -> agbox.v1.SandboxOwner
	18, // 25: agbox.v1.ListSandboxesResponse.sandboxes:type_name -> agbox.v1.SandboxHandle
	9,  // 26: agbox.v1.CreateExecRequest.env_overrides:type_name -> agbox.v1.KeyValue
	8,  // 27: agbox.v1.CreateExecRequest.caller_metadata:type_name -> agbox.v1.CallerMetadata
	20, // 28: agbox.v1.GetExecResponse.exec:type_name -> agbox.v1.ExecStatus
	20, // 29: agbox.v1.ListActiveExecsResponse.execs:type_name -> agbox.v1.ExecStatus
	5,  // 30: agbox.v1.SandboxService.Ping:input_type -> agbox.v1.PingRequest
	21, // 31: agbox.v1.SandboxService.CreateSandbox:input_type -> agbox.v1.CreateSandboxRequest
	23, // 32: agbox.v1.SandboxService.GetSandbox:input_type -> agbox.v1.GetSandboxRequest
	25, // 33: agbox.v1.SandboxService.ListSandboxes:input_type -> agbox.v1.ListSandboxesRequest
	27, // 34: agbox.v1.SandboxService.ResumeSandbox:input_type -> agbox.v1.ResumeSandboxRequest
	28, // 35: agbox.v1.SandboxService.StopSandbox:input_type -> agbox.v1.StopSandboxRequest
	29, // 36: agbox.v1.SandboxService.DeleteSandbox:input_type -> agbox.v1.DeleteSandboxRequest
	31, // 37: agbox.v1.SandboxService.SubscribeSandboxEvents:input_type -> agbox.v1.SubscribeSandboxEventsRequest
	32, // 38: agbox.v1.SandboxService.CreateExec:input_type -> agbox.v1.CreateExecRequest
	34, // 39: agbox.v1.SandboxService.CancelExec:input_type -> agbox.v1.CancelExecRequest
	35, // 40: agbox.v1.SandboxService.GetExec:input_type -> agbox.v1.GetExecRequest
	37, // 41: agbox.v1.SandboxService.ListActiveExecs:input_type -> agbox.v1.ListActiveExecsRequest
	6,  // 42: agbox.v1.SandboxService.Ping:output_type -> agbox.v1.PingResponse
	22, // 43: agbox.v1.SandboxService.CreateSandbox:output_type -> agbox.v1.CreateSandboxResponse
	24, // 44: agbox.v1.SandboxService.GetSandbox:output_type -> agbox.v1.GetSandboxResponse
	26, // 45: agbox.v1.SandboxService.ListSandboxes:output_type -> agbox.v1.ListSandboxesResponse
	30, // 46: agbox.v1.SandboxService.ResumeSandbox:output_type -> agbox.v1.AcceptedResponse
	30, // 47: agbox.v1.SandboxService.StopSandbox:output_type -> agbox.v1.AcceptedResponse
	30, // 48: agbox.v1.SandboxService.DeleteSandbox:output_type -> agbox.v1.AcceptedResponse
	19, // 49: agbox.v1.SandboxService.SubscribeSandboxEvents:output_type -> agbox.v1.SandboxEvent
	33, // 50: agbox.v1.SandboxService.CreateExec:output_type -> agbox.v1.CreateExecResponse
	30, // 51: agbox.v1.SandboxService.CancelExec:output_type -> agbox.v1.AcceptedResponse
	36, // 52: agbox.v1.SandboxService.GetExec:output_type -> agbox.v1.GetExecResponse
	38, // 53: agbox.v1.SandboxService.ListActiveExecs:output_type -> agbox.v1.ListActiveExecsResponse
	42, // [42:54] is the sub-list for method output_type
	30, // [30:42] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		EnumInfos:         file_service_proto_enumTypes,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
